### ISSUE TITLE
add where to find python soundfile module

### ISSUE THREAD

**Issue by ycollet** [Vampouille/superboucle#19]
soundfile module is not shipped by fedora.
Please, add in the documentation where to find soundfile, or embeds it in the superboucle repo

**Comment by Vampouille** [comment]
In order to install PySoundFile, you need CFFI and NumPy package did you successfully install those packages ?
Then, you need libsndfile system package. In fedora you have this package : 
https://apps.fedoraproject.org/packages/libsndfile
and this package :
https://apps.fedoraproject.org/packages/libsndfile-devel
So I think you just need to install libsndfile and libsndfile-devel packages

**Comment by Vampouille** [comment]
Can you confirm that it's working on fedora ?

**Comment by ycollet** [comment]
Sorry, I haven't found the time to test it. I will test this on thursday evening.
Best regards

**Comment by Vampouille** [comment]
A new version is available on sourceforce : 1.1.0 :
http://downloads.sourceforge.net/project/superboucle/SuperBoucle-1.1.0.tgz

Now, you can record with superboucle.

**Comment by ycollet** [comment]
Hello,

All the packages are installed but I still have an error related to the soundfile module:

$ make
./boucle.py
Traceback (most recent call last):
  File "./boucle.py", line 7, in <module>
    from clip import Clip, Song
  File "/home/collette/repositories/superboucle/clip.py", line 2, in <module>
    import soundfile as sf
ImportError: No module named 'soundfile'
Makefile:6: recipe for target 'run' failed
make: *** [run] Error 1

**Comment by ycollet** [comment]
Do you use this package: https://pypi.python.org/pypi/PySoundFile

**Comment by ycollet** [comment]
To install the dependency: pip install pysoundfile

**Comment by ycollet** [comment]
And because superboucle uses python3, under fedora, as a root user: pip3 install pysoundfile (you need to install the pip3 package before).

**Comment by Vampouille** [comment]
Yes those instructions are in requirement part of readme file, not install part. I need to rewrite this part. This is the python module part :

`sudo pip3 install cffi` (maybe you can use system package, tested with version 0.9.2)
`sudo pip3 install numpy` (again you can try system package, tested with 1.9.2)
`sudo pip3 install PySoundFile` (this need libsndfile system libs)

**Comment by ycollet** [comment]
It's OK for me. I leave you close this bug ?

**Comment by Vampouille** [comment]
ok, Thanks for feedback

**Comment by fenderrex** [comment]
can some one please update the setup.py?

**Comment by Vampouille** [comment]
Maybe I can add sometime like this :
```python
#!/usr/bin/env python

from distutils.core import setup

setup(name='SuperBoucle',
      version='1.2.0',
      description='SuperBoucle is a loop based software fully controllable with any midi device. SuperBoucle is also synced with jack transport. You can use it on live performance or for composition.',
      author='Julien Acroute',
      author_email='superboucle@nura.eu',
      url='https://github.com/Vampouille/superboucle/',
      packages=['Cffi', 'PySoundFile', 'Numpy', 'PyQT 5'],
     )
```
But I don't known how to write module name : 'PyQT 5' or 'pyqt5' or 'PyQT5' ?

**Comment by jageshmaharjan** [comment]
Did you install everything in doc/requirements.txt file.
Had the same issue, after i install packages in "requirements.txt", everything worked for me.

**Comment by Vampouille** [comment]
> Did you install everything in doc/requirements.txt file.

There is no requirements.txt file but something here : https://github.com/Vampouille/superboucle#linux-1

Can you provide a simple requirements.txt ?

**Comment by mohammedyunus009** [comment]
In my case i installed 
`pip install pysoundfile`
but imported it as 
`import soundfile`
it worked for me
