### ISSUE TITLE
No module named 'gui_ui'

### ISSUE THREAD

**Issue by wargreen** [Vampouille/superboucle#23]
Hi,
After install all modules via pip, as in the README, I got

 Traceback (most recent call last):
  File "boucle.py", line 8, in <module>
    from gui import Gui
  File "/home/wargreen/Téléchargements/Audio/superboucle/gui.py", line 12, in <module>
    from gui_ui import Ui_MainWindow
ImportError: No module named 'gui_ui'

**Comment by Vampouille** [comment]
Hello, 

I think you try to launch superboucle from dev archive. Did you download a release version 1.1.0 ?

Release versions contains modules like gui_ui, so first solution is to download last release here :
https://github.com/Vampouille/superboucle/releases

If you want to run dev version, you will have to generate those module with `make run` command. For this, you will need PyQT5 dev tools.
