### ISSUE TITLE
ZeroDivisionError: float divmod()

### ISSUE THREAD

**Issue by wargreen** [Vampouille/superboucle#25]
Divise beat by zero return 
From cffi callback <function Client.set_process_callback.<locals>.callback_wrapper at 0x7f25d246bbf8>:
Traceback (most recent call last):
  File "/opt/SuperBoucle-1.1.0/jack.py", line 878, in callback_wrapper
    return callback(frames)
  File "boucle.py", line 65, in my_callback
    clip.beat_diviser)
ZeroDivisionError: float divmod()

**Comment by Vampouille** [comment]
Can you retry with last 1.2.0 version, I just added some check to fix your issue :

https://github.com/Vampouille/superboucle/releases/download/1.2.0/SuperBoucle-1.2.0.tgz

**Comment by Vampouille** [comment]
Are you using mac osx ?

**Comment by wargreen** [comment]
It work !
I use Debian SID x64.
