### ISSUE TITLE
Invalid message length with Aftertouch messages

### ISSUE THREAD

**Issue by wargreen** [Vampouille/superboucle#26]

**Comment by Vampouille** [comment]
Can you give me error message ? did you just get "Invalid message length" in terminal ? is it working ?

**Comment by wargreen** [comment]
I got only this message in my terminal., and impossible to learn.
This appen with a MPD24.

**Comment by Vampouille** [comment]
Can you try to disable aftertouch feature ? you can also try with [FULL LEVEL] option activated.
For learning did you click on "Learn first line" button ?

**Comment by wargreen** [comment]
It seem to be fixed with the new version !
