### ISSUE TITLE
Separate gui from data?

### ISSUE THREAD

**Issue by IARI** [Vampouille/superboucle#28]
How would you feel about separating the gui from the data a bit?
i.e. make a class that holds
- playlist
- devices
- song
- portlist
- ..

while the gui just keeps in charge of the state of the main window itsself?

I felt I wouldn't to do this in the fork, because its a little more of a basic change so it would feel right to pull it from upstream, but if you find it a good ide but don't want to do it yourself i would still do it

**Comment by Vampouille** [comment]
The gui.py file should be shorter, it's a good idea to move some code from gui file to other files. About classes, we have already a class for devices and songs (and portlist is implemented in song class). Can show me some piece of code that should not be in gui file ?
