### ISSUE TITLE
Device Midi

### ISSUE THREAD

**Issue by CyBerNetX** [Vampouille/superboucle#30]
i have buy a Akai APC Mini and i need some help or precision for making sbm file by correct way

i have all buttons but i'm not sure for  transport button and line button 
because there is no play button but clip stop , solo, rec arm, etc like in the picture
http://6be54c364949b623a3c0-4409a68c214f3a9eeca8d0265e9266c0.r0.cf2.rackcdn.com/990/images/APCmini_ortho_web_lg.png
i think  it was for the right buttons is transport way but is there 8 vertical  button

and the line button are for the last lines (fader ctrl) etc 

and on midi set up 
thanks for reading !

**Comment by Vampouille** [comment]
Hello, 

Based on your apc picture, I will suggest you to use last column of your 8x8 buttons grid for "line buttons". With this setup, you will a matrix of 7x8 clips. Assign fader 1 to 7 to "controllers" part of "clips volume per line" and last fader (fader 9) to master volume. Then you can assign any of remaining buttons (buttons on right : clip stop, solo, ...) to transport. No matter if you assign "rec arm" to "play". The only requirement is that your apc must always send the same midi event when you press it.
Another solution for transport is to use last line of your 8x8 matrix for transport. In this way, you can assign transport function in the same order as gui.
You can also take a look at this page that contain a detailed manual : http://superboucle.nura.eu/index.php/manual/

**Comment by CyBerNetX** [comment]
thanks  
also i have translated readme.md to french 
http://www.linuxmao.org/traduction+du+README.md+du+github

**Comment by CyBerNetX** [comment]
there is a bug ?? when export device Midi and import sbm file is empty

**Comment by CyBerNetX** [comment]
AKAI_APC_Mini.sbm :

-8<-------------------------------------8<------------------------------
{"block_buttons": [[9, 0, 82, 127], [9, 0, 83, 127], [9, 0, 84, 127], [9, 0, 85, 127], [9, 0, 86, 127], [9, 0, 87, 127], [9, 0, 88, 127], [9, 0, 89, 127]], "amber_vel": 5, "init_command": [], "start_stop": [[[9, 0, 56, 127], [9, 0, 57, 127], [9, 0, 58, 127], [9, 0, 59, 127], [9, 0, 60, 127], [9, 0, 61, 127], [9, 0, 62, 127], [9, 0, 63, 127]], [[9, 0, 48, 127], [9, 0, 49, 127], [9, 0, 50, 127], [9, 0, 51, 127], [9, 0, 52, 127], [9, 0, 53, 127], [9, 0, 54, 127], [9, 0, 55, 127]], [[9, 0, 40, 127], [9, 0, 41, 127], [9, 0, 42, 127], [9, 0, 43, 127], [9, 0, 44, 127], [9, 0, 45, 127], [9, 0, 46, 127], [9, 0, 47, 127]], [[9, 0, 32, 127], [9, 0, 33, 127], [9, 0, 34, 127], [9, 0, 35, 127], [9, 0, 36, 127], [9, 0, 37, 127], [9, 0, 38, 127], [9, 0, 39, 127]], [[9, 0, 24, 127], [9, 0, 25, 127], [9, 0, 26, 127], [9, 0, 27, 127], [9, 0, 28, 127], [9, 0, 29, 127], [9, 0, 30, 127], [9, 0, 31, 127]], [[9, 0, 16, 127], [9, 0, 17, 127], [9, 0, 18, 127], [9, 0, 19, 127], [9, 0, 20, 127], [9, 0, 21, 127], [9, 0, 22, 127], [9, 0, 23, 127]], [[9, 0, 8, 127], [9, 0, 9, 127], [9, 0, 10, 127], [9, 0, 11, 127], [9, 0, 12, 127], [9, 0, 13, 127], [9, 0, 14, 127], [9, 0, 15, 127]], [[9, 0, 0, 127], [9, 0, 1, 127], [9, 0, 2, 127], [9, 0, 3, 127], [9, 0, 4, 127], [9, 0, 5, 127], [9, 0, 6, 127], [9, 0, 7, 127]]], "master_volume_ctrl": [11, 0, 56], "blink_red_vel": 4, "play_btn": [9, 0, 65, 127], "blink_amber_vel": 6, "record_btn": [9, 0, 67, 127], "blink_green_vel": 2, "name": "AKAI APC mini", "black_vel": 0, "ctrls": [[11, 0, 48], [11, 0, 49], [11, 0, 50], [11, 0, 51], [11, 0, 52], [11, 0, 53], [11, 0, 54], [11, 0, 55]], "rewind_btn": [9, 0, 64, 127], "pause_btn": [9, 0, 66, 127], "goto_btn": [9, 0, 68, 127], "green_vel": 1, "red_vel": 3}

-8<-------------------------------------8<------------------------------
the transport button are the last line circle buttons
the left column of circle button are for select the line

**Comment by Vampouille** [comment]
This commit should fix issue about importing device with sbm files : ea1967aeac626809b8ff4b0f4a7ac306471ee9ff 
Can you retry ?
You can replace your device.py file with new one : https://github.com/Vampouille/superboucle/blob/master/device.py
