### ISSUE TITLE
I don't like add_port.py

### ISSUE THREAD

**Issue by IARI** [Vampouille/superboucle#31]
Theres two things I don't really like about it:

 1. you're giving it a callback - why not handle it like the other mini-dialogs in pyqt are done: let it return asynchronously with a response
 2. on ok it handles part of what hast to be done:
```python
    self.gui.addPort(self.name.text())
```
but the other part is in the callback

Finally: why do you even need this class? whats wrong with a QInputDialog?

**Comment by Vampouille** [comment]
I don't have recheck code but I think it is because I use this dialog in manage ui and in main ui. When I use it in manage ui I need to update list of manage ui and droplist in main ui.
