### ISSUE TITLE
pep8

### ISSUE THREAD

**Issue by IARI** [Vampouille/superboucle#32]
@Vampouille
There are a few things which are not pep8 conform (i.e. some fields and functions/methods are camel case).

Would you like to endorse the full pep8 conventions?

**Comment by Vampouille** [comment]
yes, there is a mix of camelCase and lower_case. If pep8 recommend lower_case we will turn all code in lower_case.

**Comment by IARI** [comment]
yep, it does :) However you might have seen too that pyQt does not comply - they keep the camelcase convention, so I'm not sure how to handle that.
I just found a stackoverflow question on the topic
http://stackoverflow.com/questions/3647518/pep8-and-pyqt-how-to-reconcile

what do you think?

**Comment by Vampouille** [comment]
We use 2 library : QT and Jack QT prefer camelCase and jack prefer lower_case. In most case, we will use camelCase for function and keep lower_case for attribute.
