### ISSUE TITLE
FR readme.md translation

### ISSUE THREAD

**Issue by trebmuh** [Vampouille/superboucle#33]
Comme signalé par @CyBerNetX ici : https://github.com/Vampouille/superboucle/issues/30#issuecomment-124846621 , pourriez-vous vérifier la traduction du README.md  en français ( http://www.linuxmao.org/traduction+du+README.md+du+github ) afin de vérifier que tout correspond à ce que vous vouliez vraiment dire ?
Merci à CyBerNetX pour la traduction et à vous pour le logiciel !

en version anglaise : 
as mentionned by @CyBerNetX here : https://github.com/Vampouille/superboucle/issues/30#issuecomment-124846621 , could you please check the french translation of the README.md ( http://www.linuxmao.org/traduction+du+README.md+du+github ) to ensure that everything is matching what you were meaning?
Thanks to CyBerNetX for the translation and you all for the software !

**Comment by Vampouille** [comment]
I already made a french translation here :
http://www.linuxmao.org/superboucle
It should already contains all informations of readme file, maybe I can put it in a readme.md.fr ? I don't known what conventions is used on github.

**Comment by trebmuh** [comment]
Would be an idea yes.
Re: the 2 pages on linuxmao, reading at those quickly gives me the impression that the new one is covering more than the 1st one. I could be just an impression though.
I've been helping @CyBerNetX to get in touch with you and github, now my job is done and I'm leaving you guys talking together. HTH.
Cheers.

**Comment by Vampouille** [comment]
I just added a french translation in bcf953f3e2b8848d4a9e876d8c0e0ffcde7da644

**Comment by trebmuh** [comment]
Super.
