### ISSUE TITLE
application not launching

### ISSUE THREAD

**Issue by tecan** [Vampouille/superboucle#46]
have tried both with jack running and without.

Traceback (most recent call last):
  File "boucle.py", line 209, in <module>
    client.connect(record[1], inR)
IndexError: list index out of range

**Comment by Vampouille** [comment]
> client.connect(record[1], inR)
> IndexError: list index out of range

It seems that your jack setup are missing some output. Did you have a stereo output or mono configured in jack ?

Jack running is a "must have" to run superboucle. Can you try to launch patchage app after jack is started and look at system output. How many output do you have ?

**Comment by tecan** [comment]
i have 5.1 surround sound usb box. https://imagebin.ca/v/3bFjOnnzboFW

**Comment by Vampouille** [comment]
You have only one input channel and superboucle is trying to bind 2 channels for input.
You can disable auto connect feature with following config file : 

 ~/.config/superboucle/session.conf
```
[General]
auto_connect=false
```
By adding this file, you should be able to successfully launch superboucle.

**Comment by Vampouille** [comment]
@tecan is it working with previous tricks ?
