### ISSUE TITLE
gui icons not showing up

### ISSUE THREAD

**Issue by tecan** [Vampouille/superboucle#47]
i tried putting them around in different places /usr/share/icons/icons/ ~/.local/share/icons ./icons/icons nothing seemed to work.

**Comment by Vampouille** [comment]
Icons should be kept in a subfolder "icons":
https://github.com/Vampouille/superboucle/blob/master/gui_ui.py#L48
How did you launch superboucle ? Maybe you don't start superboucle from root directory of this project ?
