### ISSUE TITLE
Save Bug

### ISSUE THREAD

**Issue by sonejostudios** [Vampouille/superboucle#54]
Hey Julien! 
long time no talk ;)
I'm still using superboucle and I'm really happy with it. Now I am upgrading my system and a really strange bug came out. I' using EXACTLY the same Superboucle version on two different systems, but I get a different behaviour with the SaveTo method.

- On Ubuntu 12.04, I can save a song correctly, Superboucle saves a zip file with a "metadata.ini" and wavs inside the zip (.sbs)

- On Ubuntu 14.04 and 18.04, if I save a song, Superboucle saves a zip file with the "metadata.ini" inside, but with no wav files at all!

This is so strange because I use exactly the same Supercoucle code on both systems.

What could it be, do you have any idea? Could you test the Save To on your system and give me a feedback?

I thought maybe it is related to a new version of qt5? actually both are using qt 5.2.1, so it shouldn't be a qt issue.
Or a problem with the python3 version? the working superboucle uses python 3.2.3 while the not working version uses python 3.4.0. Could it be??

Thank you very much
All the best,
Vince

**Comment by sonejostudios** [comment]
Here the Python error:

/usr/bin/python3.4 /media/sda7/Programming/GIT/superboucle/boucle.py
Traceback (most recent call last):
  File "/media/sda7/Programming/GIT/superboucle/gui.py", line 481, in onActionSaveAs
    self.song.save()
  File "/media/sda7/Programming/GIT/superboucle/clip.py", line 250, in save
    self.saveTo(self.file_name)
  File "/media/sda7/Programming/GIT/superboucle/clip.py", line 290, in saveTo
    format='WAV')
  File "/usr/local/lib/python3.4/dist-packages/soundfile.py", line 429, in write
    channels = data.shape[1]
IndexError: tuple index out of range

**Comment by Vampouille** [comment]
> could it be the soundfile library?

The soundfile library change a little bit : https://github.com/bastibe/SoundFile/pull/133
I had to change superboucle code like this : https://github.com/Vampouille/superboucle/commit/74e95abf34092f3b37b4bce3d49c99222d2e1899 for loading song with mono file. Maybe we also need to update save code. I will check this on my side.

**Comment by sonejostudios** [comment]
Hey Vampuille, 
look what I found on the official Soundfile doc:
The argument order of write changed!

> 
> Breaking Changes
> 
> SoundFile has evolved rapidly during the last few releases. Most notably, we changed the import name from import pysoundfile to import soundfile in 0.7. In 0.6, we cleaned up many small inconsistencies, particularly in the the ordering and naming of function arguments and the removal of the indexing interface.
> 
> In 0.8.0, we changed the default value of always_2d from True to False. Also, the order of arguments of the write function changed from write(data, file, ...) to write(file, data, ...).
> 
> In 0.9.0, we changed the ctype arguments of the buffer_* methods to dtype, using the Numpy dtype notation. The old ctype arguments still work, but are now officially deprecated.

**Comment by sonejostudios** [comment]
Hey Vampouille,

I just changed the order of the arguments of the write method on my local machine and it works now perfectly ;)

**Comment by Vampouille** [comment]
> I just changed the order of the arguments of the write method on my local machine and it works now perfectly ;)

Can you add a link to the part of code you modify ?

**Comment by sonejostudios** [comment]
Here (in clip.py):

https://github.com/sonejostudios/superboucle/commit/a743a778c04cf76d1f64c52b2afb65184b0eac29 #
