### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by Zer0-** [Vampouille/superboucle#55]
I cannot find the license for this software. The website just mentions that it's "open source".

I am trying to package superboucle;  no explicit license may be a problem with it getting accepted into the repository. There are other (better) reasons to include a license.

**Comment by Vampouille** [comment]
@Zer0- this PR adds a license https://github.com/Vampouille/superboucle/pull/56

**Comment by Vampouille** [comment]
I just merge the previous PR. So code is now under GPL v3.
