### ISSUE TITLE
Can't see "scenes" management / error starting latest version

### ISSUE THREAD

**Issue by manucontrovento** [Vampouille/superboucle#65]
Hello everyone, as I just told in my previous post, I'm quite new to SuperBoucle.

I can see the "Playlist" feature but not the "scenes" management, maybe it's a feature that is not in version 1.2.0 ?
I also downloaded latest master version but an error prevents from starting:

> manu@manu-HP-EliteBook-8540w:~/Applicazioni/superboucle-master$ ./SuperBoucle.sh
> 
> Traceback (most recent call last):
>   File "superboucle/boucle.py", line 5, in <module>
>     import superboucle.jack as jack
> ModuleNotFoundError: No module named 'superboucle'
> 

Have a nice day all,
Manu

**Comment by Vampouille** [comment]
> I also downloaded latest master version but an error prevents from starting

You should set the `PYTHONPATH` env var:
```bash
export PYTHONPATH=$(pwd):$PYTHONPATH
```


> I can see the "Playlist" feature but not the "scenes" management

The scene manager was not implemented in 1.2.0 so if you use master you will have this feature:
![Capture d’écran du 2019-11-05 08-26-49](https://user-images.githubusercontent.com/7067560/68187124-1d230880-ffa6-11e9-90b8-77e7f899f051.png)

**Comment by manucontrovento** [comment]
Hi @Vampouille thanks for your replies and excuse me for late answers. 
I finally reached to start SuperBoucle master branch, I don't know if my solution is the best or if it could cause a bad management of something somewhere.... I'm quite a newbie in Linux world 

I added the line you suggested in SuperBoucle.sh starting file:

```
#!/bin/bash
export PYTHONPATH=$(pwd):$PYTHONPATH
python3 superboucle/boucle.py
```

is it right? However, it seems to work! unfortunately, something is still breaking my connections.. I'll continue on the other post.
thanks
Manu

**Comment by Vampouille** [comment]
>  I don't know if my solution is the best

It's good you're modification only affect superboucle. A more pythonic approach would be to create a virtual env and install superboucle in this virtual env. But if it works for you this way it's fine. You will have issue only if you install other python that needs the same library but with another version.
