### ISSUE TITLE
a minor issue: <Quit> menu command not working

### ISSUE THREAD

**Issue by manucontrovento** [Vampouille/superboucle#66]
Hi,
this is obviously not important, it's just to take a note about it: from the window menu, Quit command doesn't work, I alway close SB from the upper right "X" window control.

[OT]: where could I post my contributions? I'd like to send you my AKAI APC 25 controller script, and other things I could produce (e.g. an Italian translation of the manual, and maybe of the user interfaces)

have a nice day
manu

**Comment by Vampouille** [comment]
> where could I post my contributions?

You can create a pull request with your modifications if known how to do it. Alternatively, you can just post files (translated readme, akai controller config) here I will create the pull for you.

**Comment by Vampouille** [comment]
> from the window menu, command doesn't work

I will check this issue

**Comment by manucontrovento** [comment]
> 
> 
> > where could I post my contributions?
> 
> You can create a pull request with your modifications if known how to do it. Alternatively, you can just post files (translated readme, akai controller config) here I will create the pull for you.

Ok... sorry about it, I didn't understand how to make a pull request.. but if you tell me, I can make it.

**Comment by Vampouille** [comment]
> if you tell me, I can make it.

* Fork the superboucle repo on github : you have a fork button
* Clone the new repo on your workstation : `git clone https://github.com/manucontrovento/superboucle.git`
* Add files locally,
* create a branch `git checkout -b add_files`
* add files to git `git add <files you just added>`,
* `git commit`
* push your modification to github `git push origin add_files`
* The previous should give you a link, follow this link to create a pull request on github
* Be sure to select "vampouille" as the target repository
* Finally, wait for comments on your pull requests

You can also take a look at https://github.com/firstcontributions/first-contributions

**Comment by Vampouille** [comment]
Fix with https://github.com/Vampouille/superboucle/commit/029952b5298e7204d93f6c7386437ed964e2ed63
