### ISSUE TITLE
[minor suggestion] Enter clip details, when triggered

### ISSUE THREAD

**Issue by manucontrovento** [Vampouille/superboucle#68]
Hello, it could be useful maybe, when a clip is triggered, to automatically "select" it and see its details on the left bottom panel, so that if it sounds too weak or too loud, I can see what its volume level is, and adjust it (with its proper knob e.g.)

**Comment by Vampouille** [comment]
Sometimes, many clips are triggered at the same time, how to handle this ?

**Comment by manucontrovento** [comment]
mybe , in this case (e.g. triggering a scene) nothing should change. Maybe entering the clip detail makes sense only triggering the single clip. Just to see its proper volume level change - so it's alreday focused.

**Comment by manucontrovento** [comment]
I'm working on it on my own, so I can close this thread.
