### ISSUE TITLE
Start playing a clip after recorded

### ISSUE THREAD

**Issue by manucontrovento** [Vampouille/superboucle#69]
Hi,
I'm starting doing my tests to recording too. 
Step by step I'm getting ready to get on stage.
I think it could be very useful that a clip would start playing immediately after recorded. Or, at least, introducing a flag which defines this behaviour (possibly True by default)
In fact, if you are playing some notes on the bass, when recorded, it could be nice that the bass line automatically continues, not breaking the groove.
This is an example but there are many cases in which it could be nice that the loops continues after recorded
cheers
manu

**Comment by Vampouille** [comment]
> In fact, if you are playing some notes on the bass, when recorded, it could be nice that the bass line automatically continues, not breaking the groove.

Agree, this is the behaviour of some loop pedal.

**Comment by manucontrovento** [comment]
I'm working on it on my own, so I can close this thread.
