### ISSUE TITLE
Cleaning MIDI device pads when entering/quitting SB

### ISSUE THREAD

**Issue by manucontrovento** [Vampouille/superboucle#70]
Hi,

it could be nice if SB automatically would "clean" the pads of MIDI controller, just like when you delete a clip. I know that on MIDI learning there's an option to send some MIDI reset commands, but if I don't know the reset sequence on my controller, and I can't find anywhere on internet, when quitting SB, the pads stay lighted-on on controller and I have to disconnect it to reset it.

Cheers
Manu

**Comment by Vampouille** [comment]
I cannot find a reset MIDI message for your device, anyway, SB can light-off all cells that are managed.

**Comment by manucontrovento** [comment]
maybe you could just insert in SB menu a shortcut to the same command which you already use in MIDI Learning, to reset all the pads. So that when pads don't reset, it's always possible in any moment to call the command. There also could be a flag somewhere to automatically send the command when entering / leaving SB

**Comment by manucontrovento** [comment]
Sorry, I'll explain better: I mean, using the same feature that you use in midi learning, setting the colors, so set all the buttons like not-assigned (and so, light-off)

**Comment by manucontrovento** [comment]
I'm working on it on my own, so I can close this thread.
