### ISSUE TITLE
SuperBoucle and Gladish

### ISSUE THREAD

**Issue by manucontrovento** [Vampouille/superboucle#79]
Hi everyone! 
I was trying to configure a Studio in Gladish, to keep all connections saved ad applications connected, not to make the connections every time I use SB.
Has anyone some experience about that?

When I try to run the Application (SB) in the Gladish studio, an error occurs and SB won't start.

When a Studio is running:

- Application -> New Application, which opens the new application dialog
- I set the Command (/home/.../SuperBoucle/./SuperBoucle.sh)
- Flag on "Run in terminal", then select Level 0 or Level 1

..and trying to start the application, the message from Gladish is: "App terminated unexpectedly"

Could anyone find out more?
Thanks - have a nice day
manu

**Comment by trebmuh** [comment]
try with "sh /home/.../SuperBoucle/./SuperBoucle.sh"

**Comment by manucontrovento** [comment]
I tried, thanks, but same result...

**Comment by Vampouille** [comment]
@manucontrovento You can add a `read` instruction at the end of the `SuperBoucle.sh` script so you can view error messages.
I think it's an issue regarding the working dir, the directory where the script runs.
Can you test with the following `Superboucle.sh`:
```bash
#!/bin/bash
SCRIPTPATH="$( cd "$(dirname "$0")" ; pwd -P )"
cd $SCRIPTPATH
export PYTHONPATH=$(pwd):$PYTHONPATH
python3 superboucle/boucle.py
read
```

**Comment by manucontrovento** [comment]
Ok, now with this .sh the application starts. I see some errors, output is like this:

> ERROR: ld.so: object 'libasound.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
> ERROR: ld.so: object 'libasound.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
> ERROR: ld.so: object 'libasound.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
> ERROR: ld.so: object 'libasound.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
> ERROR: ld.so: object 'libasound.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
> qt5ct: using qt5ct plugin
> qt5ct: D-Bus global menu: no

**Comment by manucontrovento** [comment]
Solved using a shell script to load all applications + Carla to maintain connections
