### ISSUE TITLE
UI strange behaviour and font scaling

### ISSUE THREAD

**Issue by manucontrovento** [Vampouille/superboucle#81]
Hi everyone,

in master branch release, I can't see anymore the icons on trasport buttons (I think in 1.2.0 release, the images were displayed)

and when entering the clip details (edit) fonts seem to be out of size; this may be a consequence maybe of a font scaling set in operative system. It could be a nice idea , in some way, preventing the fonts to be scaled, in the edit window (maybe it's useful to apply font scaling to upper menu)

**Comment by trebmuh** [comment]
If that can helps to target the issue, superboucle from GIT master 0a76441, build on Debian Buster, I can see transport buttons.

**Comment by manucontrovento** [comment]
@trebmuh I tried, dowloading application again, but nothing changes.. I still believe it could depend on some o.s. issue; it would be nice preventing the fonts and scaling to change, despite of o.s. font settings

**Comment by manucontrovento** [comment]
I'm working on it on my own, so I can close this thread.
