### ISSUE TITLE
Keyboard Shortcuts to load next/previous scene and song

### ISSUE THREAD

**Issue by manucontrovento** [Vampouille/superboucle#82]
Hi everyone, this is a minor suggestion. 
It would be nice to have some shortcuts to quickly select next or previous scene/song from the list.

e.g.
F5 select and load previous scene from scene manager
F6 select and load next scene from scene manager
F7 select and load previous song from playlist editor
F8 select and load next song from playlist editor

updating the current element in the list too

**Comment by Vampouille** [comment]
> updating the current element in the list too

Can you explain ? Do you mean updating the scene manager window according to the current scene .

**Comment by manucontrovento** [comment]
Yes!

**Comment by manucontrovento** [comment]
I'm working on it on my own, so I can close this thread.
