### ISSUE TITLE
Ableton Link support

### ISSUE THREAD

**Issue by grammoboy2** [Vampouille/superboucle#85]
https://github.com/Ableton/link
https://github.com/rncbc/jack_link
https://github.com/falkTX/Hylia/blob/master/hylia.h
https://media.ccc.de/v/lac2018-42-ableton_link_a_technology_to_synchronize_music_software

**Comment by grammoboy2** [comment]
Using jack_link seems to work
https://linuxmusicians.com/viewtopic.php?f=19&t=22430

**Comment by Vampouille** [comment]
Feel free to reopen this issue with a detailed description.
